apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awssecrets.acamillo.github.com
spec:
  group: acamillo.github.com
  names:
    kind: AWSSecret
    listKind: AWSSecretList
    plural: awssecrets
    singular: awssecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - secretsManagerRef
          properties:
            secretsManagerRef:
              type: object
              required:
                - secretId
                - versionId
              properties:
                secretId:
                  type: string
                versionId:
                  type: string

        status:
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
