apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-secret-operator
  template:
    metadata:
      labels:
        name: aws-secret-operator
    spec:
      serviceAccountName: aws-secret-operator
      containers:
        - name: aws-secret-operator
          image: acamillo/aws-secret-operator:0.0.1
          command:
            - aws-secret-operator
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - mountPath: /.aws
              name: aws-credentials-volume
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-secret-operator"
            - name: AWS_SDK_LOAD_CONFIG
              value: "1"
            - name: AWS_DEFAULT_PROFILE
              value: "default"
            - name: AWS_REGION
              value: "us-east-1"

      volumes:
        - name: aws-credentials-volume
          hostPath:
            # directory location on host
            path: /.aws
            # this field is optional
            type: Directory

